spring.application.name=workflow-tramites
spring.data.mongodb.uri=mongodb://localhost:27017/test
server.port=8081
# Gemini AI API Key - No subir este archivo a repositorios publicos
gemini.api.key=AIzaSyDrjIKurpsPfnnLX4B10W1mfI9xkJD5wFc, AIzaSyCbo34cvA19gc-5WiRHQqQPWg1Z9xMMKJE, AIzaSyAWNpmoJ_Qsfb2gRuWDrcHKlZzY5TmE81U, AIzaSyDk-OhYMcs9B_SVe8xpd9HSxq5TgZz3ET4
